"""Vendor-neutral immutable domain models (re-exported from core)."""

from chew.core.models import (
    Chapter,
    ChapterSummary,
    Claim,
    Evidence,
    EvidenceCandidate,
    EvidenceValidationResult,
    ExecutionPlan,
    FrozenModel,
    GenerationRequest,
    GenerationResult,
    KnowledgePack,
    Provenance,
    SourceIdentity,
    SourceKind,
    TaskRoute,
    Topic,
    TopicSummary,
    Transcript,
    TranscriptSegment,
    ValidatedEvidenceRef,
)

__all__ = [
    "Chapter",
    "ChapterSummary",
    "Claim",
    "Evidence",
    "EvidenceCandidate",
    "EvidenceValidationResult",
    "ExecutionPlan",
    "FrozenModel",
    "GenerationRequest",
    "GenerationResult",
    "KnowledgePack",
    "Provenance",
    "SourceIdentity",
    "SourceKind",
    "TaskRoute",
    "Topic",
    "TopicSummary",
    "Transcript",
    "TranscriptSegment",
    "ValidatedEvidenceRef",
]
